server:
  port: 18004
spring:
  application:
    name: structure-admin-service
  datasource:
    username: admin
    password: ZsS6XeXisst4ZWP5
    url: jdbc:mysql://39.97.124.2:3306/admin?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai   #&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
structure:
  jwt:
    secret: 12345646
    antMatchers:
      unAuthenticated:
      # 不经过身份验证的接口
      - /login
      - /doc.html
      - /webjars/**
      - /swagger-resources/**
      - /v2/api-docs/**
  log:
    aop:
      expression: execution(public * cn.structure.sa.controller..*Controller.*(..))
swagger:
  title: 集成后台API
  description: structure-admin 集成后台API
  version: v1.0.1