CREATE TABLE `announcement` (
                                `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                `subject` varchar(128) NOT NULL COMMENT '主题',
                                `content` varchar(1024) NOT NULL COMMENT '内容',
                                `scope` int NOT NULL COMMENT '作用域: 1 app、2 管理端',
                                `type` int NOT NULL COMMENT '类型：1长期、2短期',
                                `is_top` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否置顶:0否 1是',
                                `expiration_time` datetime NOT NULL COMMENT '失效时间',
                                `state` int NOT NULL DEFAULT '1' COMMENT '状态：1正常，2失效',
                                `organization_id` bigint DEFAULT NULL,
                                `create_time` datetime(3) NOT NULL COMMENT '创建时间',
                                `update_time` datetime(3) NOT NULL COMMENT '修改时间',
                                `create_by` bigint DEFAULT NULL,
                                `update_by` bigint DEFAULT NULL,
                                `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除 0-否 1-是',
                                PRIMARY KEY (`id`),
                                KEY `idx_scope` (`scope`),
                                KEY `idx_state` (`state`),
                                KEY `idx_is_top` (`is_top`),
                                KEY `idx_expiration_time` (`expiration_time`),
                                KEY `idx_create_time` (`create_time`),
                                KEY `idx_organization_id` (`organization_id`),
                                KEY `idx_scope_organization_top_time` (`scope`,`organization_id`,`is_top`,`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='系统公告';


CREATE TABLE `operation_record` (
                                    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                    `mid` bigint NOT NULL COMMENT '成员ID',
                                    `action` varchar(128) NOT NULL COMMENT '操作行为',
                                    `module` int NOT NULL COMMENT '操作模块',
                                    `score` bigint NOT NULL COMMENT '积分变动',
                                    `operation_params` text COMMENT '操作参数',
                                    `operation_result` text COMMENT '操作结果',
                                    `status` int DEFAULT '1' COMMENT '操作状态：1成功 0失败',
                                    `error_msg` text COMMENT '错误信息',
                                    `ip_address` varchar(45) DEFAULT NULL COMMENT '操作IP',
                                    `user_agent` varchar(500) DEFAULT NULL COMMENT '用户代理',
                                    `cost_time` bigint DEFAULT NULL COMMENT '耗时(毫秒)',
                                    `organization_id` bigint DEFAULT NULL,
                                    `create_time` datetime(3) NOT NULL COMMENT '创建时间',
                                    `update_time` datetime(3) NOT NULL COMMENT '修改时间',
                                    `create_by` bigint DEFAULT NULL,
                                    `update_by` bigint DEFAULT NULL,
                                    `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除 0-否 1-是',
                                    PRIMARY KEY (`id`),
                                    KEY `idx_mid` (`mid`),
                                    KEY `idx_module` (`module`),
                                    KEY `idx_create_time` (`create_time`),
                                    KEY `idx_status` (`status`),
                                    KEY `idx_mid_module_time` (`mid`,`module`,`create_time`),
                                    KEY `idx_organization_id` (`organization_id`),
                                    KEY `idx_organization_action` (`organization_id`,`action`),
                                    KEY `idx_organization_status_time` (`organization_id`,`status`,`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='操作日志表';
